# The URL the site will be built for
base_url = "https://pure.aruoshui.fun"

# The site title and description; used in feeds by default.
title = "Aruoshui"
description = "This is an example description"
build_search_index = false
generate_feeds = true
compile_sass = true
minify_html = false
taxonomies = [{ name = "tags" }]

# Theme configuration
theme = "apollo"

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]

[markdown.highlighting]
style = "class"
dark_theme = "tokyonight_storm"
light_theme = "tokyonight_day"
extra_themes = [
  "syntax_themes/tokyonight_storm.zola-theme.json",
  "syntax_themes/tokyonight_day.zola-theme.json",
]
extra_grammars = []



[extra]
theme = "toggle"
toc = true
use_cdn = false
favicon = "/icon/code.svg"
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/Zhruoshui/zola-ruoshui/tree/main/content/"
search = true


socials = [
    { name = "bilibili", url = "https://space.bilibili.com/318903228", icon = "bilibili" },
    { name = "github", url = "https://github.com/Zhruoshui", icon = "github" },
    { name = "hexo_blog", url = "https://blog.aruoshui.fun/", icon = "hexo" },
    { name = "outlook_mail", url = "mailto:Aruoshui_ZH@outlook.com", icon = "microsoft-outlook" },
    { name = "rss", url = "/atom.xml", icon = "rss" }
]
menu = [
  { name = "/posts", url = "/posts", weight = 1 },
  { name = "/tags", url = "/tags", weight = 2 },
  { name = "/archive", url = "/archive", weight = 3 },
  { name = "/projects", url = "/projects", weight = 4 },
  { name = "/talks", url = "/talks", weight = 5 },
]

stylesheets = [
  "pagefind-search.css",
  "ref-card.css",
]

# See this for more options: https://github.com/not-matthias/apollo/blob/main/config.toml#L14

[extra.analytics]
enabled = true 

[extra.analytics.umami]
website_id = "5efa1c52-82d6-445f-ad15-c692609d8900"                    # Your Umami website ID
host_url = "https://stats.aruoshui.fun"            # Optional: Custom host URL
