name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency: deploy-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. 检出仓库
        uses: actions/checkout@v4
        with:
          ref: main

      - name: 2. 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.0"

      - name: 2.1 缓存 npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: 3. 安装 Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.21.0

      - name: 4. 安装 Pagefind
        run: |
          npm install -g pagefind@1.4.0

      - name: 5. 生成静态文件
        run: |
          zola build
          pagefind --site public/

      - name: 6. 推送到服务器私有仓库
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_PATH }}
          EXCLUDE: ".git/,.user.ini"
